//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    public partial class chat
    {
        /// <summary>
        /// hfHostId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfHostId;

        /// <summary>
        /// hfPropId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfPropId;

        /// <summary>
        /// hfCustId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfCustId;

        /// <summary>
        /// hostInitialDiv control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl hostInitialDiv;

        /// <summary>
        /// lblHostName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblHostName;

        /// <summary>
        /// lblPropertyName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPropertyName;

        /// <summary>
        /// lblError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblError;

        /// <summary>
        /// rptMessages control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptMessages;

        /// <summary>
        /// pnlEmptyChat control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlEmptyChat;

        /// <summary>
        /// txtMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtMessage;

        /// <summary>
        /// btnSend control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSend;
    }
}
